name: github_app
description: A new Flutter macOS desktop app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  fluttericon: ^2.0.0
  gql: ^0.13.0
  gql_exec: ^0.4.1-alpha+1645284956061
  gql_http_link: ^0.4.0
  gql_link: ^0.4.0
  http: ^0.13.4
  oauth2: ^2.0.0
  url_launcher: ^6.0.20
  window_to_front:
    path: ../window_to_front

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  gql_build: ^0.4.1-alpha+1645284956149

flutter:
  uses-material-design: true
