name: playground
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-alpha.2
  flutter_localizations:
    sdk: flutter
  http: ^0.13.4
  provider: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  test: ^1.19.5
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  generate: true
